version = 0.1
[default.deploy.parameters]
stack_name = "llrt-aws-sam-example"
resolve_s3 = true
s3_prefix = "llrt-aws-sam-example"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
